{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "imgtag.fullname" . }}
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "imgtag.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.oidcClientSecret.value }}
  {{ .Values.secrets.oidcClientSecret.secretKey }}: {{ .Values.secrets.oidcClientSecret.value | b64enc }}
  {{- end }}
{{- end -}}