{{- if .Values.jobs.migrate.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "parlance.fullname" . }}-migrate
  labels:
    {{- include "parlance.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "8"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "migrate"]
          {{- include "parlance.environment" . | nindent 10 }}
      restartPolicy: Never
  backoffLimit: {{ .Values.jobs.migrate.backoffLimit | default 5 }}
{{- end }}
{{- if and .Values.jobs.migrate.create .Values.jobs.ensureAdmin.create }}
---
{{- end }}
{{- if .Values.jobs.ensureAdmin.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "parlance.fullname" . }}-ensure-admin
  labels:
    {{- include "parlance.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "16"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "manage.py", "ensureadmin"]
          {{- include "parlance.environment" . | nindent 10 }}
      restartPolicy: Never
  backoffLimit: {{ .Values.jobs.ensureAdmin.backoffLimit | default 5 }}
{{- end }}