{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "parlance.fullname" . }}
  labels:
    {{- include "parlance.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.secretKey.value }}
  {{ .Values.secrets.secretKey.secretKey }}: {{ .Values.secrets.secretKey.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.databaseURL.value }}
  {{ .Values.secrets.databaseURL.secretKey }}: {{ .Values.secrets.databaseURL.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.adminPassword.value }}
  {{ .Values.secrets.adminPassword.secretKey }}: {{ .Values.secrets.adminPassword.value | b64enc }}
  {{- end }}
{{- end }}
