{{- if .Values.quarterdeck.securitytxt.text -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarterdeck.name" . }}-securitytxt
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  security.txt: {{ .Values.quarterdeck.securitytxt.text | b64enc }}
{{- end -}}
{{- $we := include "quarterdeck.welcomeEmail" . | fromYaml -}}
{{- if and .Values.quarterdeck.securitytxt.text $we.create }}
---
{{ end -}}
{{- if $we.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarterdeck.app.welcomeEmail.configMap.name" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ $we.textTemplate.key }}: |+
    {{ $we.textTemplate.value | nindent 4 }}
  {{ $we.htmlTemplate.key }}: |+
    {{ $we.htmlTemplate.value | nindent 4 }}
{{- end -}}
