{{- if and .Values.authentication.keys .Values.authentication.keysSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quarterdeck.name" . }}-keys
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quarterdeck.labels" . | nindent 4 }}
type: Opaque
stringData:
    {{ .Values.authentication.keys }}
{{- end }}