apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoping.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geoping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.grpc.type }}
  ports:
    - port: {{ .Values.services.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.services.grpc.protocol }}
      name: grpc
  selector:
    {{- include "geoping.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geoping.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geoping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.web.type }}
  ports:
    - port: {{ .Values.services.web.port }}
      targetPort: web
      protocol: {{ .Values.services.web.protocol }}
      name: web
  selector:
    {{- include "geoping.selectorLabels" . | nindent 4 }}