{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.secrets.databaseURL.value }}
  {{ .Values.secrets.databaseURL.secretKey }}: {{ .Values.secrets.databaseURL.value | b64enc }}
  {{- end }}
{{- end -}}