{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "genoa.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
  annotations:
    {{- include "genoa.annotations" (dict "lifecycle" .Release.Service "order" .Values.serviceAccount.ordering) | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceAccount.role.name | default (include "genoa.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
  annotations:
    {{- include "genoa.annotations" (dict "lifecycle" .Release.Service "order" .Values.serviceAccount.role.ordering) | nindent 4 }}
    {{- with .Values.serviceAccount.role.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccount.roleBinding.name | default (include "genoa.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
  annotations:
    {{- include "genoa.annotations" (dict "lifecycle" .Release.Service "order" .Values.serviceAccount.roleBinding.ordering) | nindent 4 }}
    {{- with .Values.serviceAccount.roleBinding.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "genoa.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ .Values.serviceAccount.role.name | default (include "genoa.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
