# Default values for deploying Parlance.
# Declare your specific configuration values in a YAML file and pas it to Helm.

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# The number of replicas to run for the Parlance deployment.
# NOTE: this chart does not allow for autoscaling at this time.
replicaCount: 1

image:
  repository: rotationalio/parlance
  pullPolicy: Always
  tag: ""   # The default image tag is the chart appVersion.

imagePullSecrets: []

# Parlance specific configuration.
parlance:
  django:
    debug: "False"
    settingsModule: parlance.settings.container
  sentry:
    dsn: ""

# Web application secrets can be created by the chart (not recommended) by setting the
# create flag to true (note that the secretName won't be used in this case). Otherwise,
# specify the secretName and secretKey rather than a value for each secret item and
# create the secret(s) manually.
secrets:
  create: true  # Set to false to use an pre-installed secret instead.
  secretKey:
    secretName: ""
    secretKey: secretKey
    value: ""
  databaseURL:
    secretName: ""
    secretKey: databaseURL
    value: ""
  adminPassword:
    secretName: ""
    secretKey: adminPassword
    value: ""

# Jobs that can be configured to run in Parlance to migrate the database or ensure
# an admin user is created with the specified adminPassword.
jobs:
  migrate:
    create: true
  ensureAdmin:
    create: true
    username: admin
    email:

# Specify how pods are created in the deployment.
pod:
  # Add additional annotations to the pods
  annotations: {}

  # Add additional labels to the pods
  labels: {}

  # Specify a pod security context
  securityContext: {}

# Optionally specify the security context of the container.
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: parlance.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# The liveness probe requires Parlance to be running.
livenessProbe:
  httpGet:
    path: /livez
    port: 8000
    httpHeaders:
    - name: X-Kubernetes-Probe
      value: liveness
  initialDelaySeconds: 2
  periodSeconds: 10

# The readiness probe requires Parlance to be running and connected to the database.
readinessProbe:
  httpGet:
    path: /readyz
    port: 8000
    httpHeaders:
    - name: X-Kubernetes-Probe
      value: readiness
  initialDelaySeconds: 2
  periodSeconds: 10

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Optionally specify how nodes are selected to place pods on.
nodeSelector: {}

# Optionally specify tolerations to ensure pods are not scheduled on incompatible nodes.
tolerations: []

# Optionally specify affinities to ensure pods and resources are together or apart.
affinity: {}
