endeavor:
  origin: "https://endeavor.example.com"
  allowOrigins:
    - "https://endeavor.example.com"
    - "https://auth.example.com"
  auth:
    quarterdeckURL: "https://auth.example.com"
    audience: "https://endeavor.example.com"

secrets:
  create: true
  inferenceAPIKey:
    value: "inferenceapikey"

ingress:
  enabled: true
  hosts:
    - host: endeavor.example.com
      paths:
        - path: /
          pathType: Prefix
    - host: endeavor.example.dev
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    memory: "32Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

volumeClaimTemplates:
  # The node data spec will be included in volume claim templates.
  nodeData:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi

# set readinessProbe and livenessProbe to null to prevent connection to db.
readinessProbe: null
livenessProbe: null

quarterdeck:
  enabled: true
  authentication:
    audience:
    - "rotational.app"
    - "auth.rotational.app"
    - "honu.rotational.app"

  securitytxt:
    text: |
      Contact: mailto:security@example.com
      Expires: 2037-11-14T22:07:00.000Z
      Encryption: https://example.com/pgp-key.txt
      Preferred-Languages: en
      Canonical: https://example.com/.well-known/security.txt
      Policy: https://example.com/security


  # Configuration for the Quarterdeck ingress.
  ingress:
    enabled: true
    hosts:
      - host: quarterdeck.svc.local
        paths:
          - path: /
            pathType: Prefix


  volumeClaimTemplates:
    database:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi