global:
  origins:
  - http://quarterdeck.svc.cluster.local
  - http://endeavor.svc.cluster.local

  issuer: "http://quarterdeck.svc.cluster.local"

endeavor:
  origin: http://endeavor.svc.cluster.local
  auth:
    quarterdeckCSRFNamespace: quarterdeck
  csrf:
    disable: false
    namespace: endeavor

secrets:
  create: true

genoa:
  enabled: true

  genoa:
    adminDatabaseURL:
      secretName: admin-database-credentials

quarterdeck:
  enabled: true
  quarterdeck:
    csrf:
      cookieDomain: tenant.example.com
