global:
  origins:
  - http://quarterdeck.svc.cluster.local
  - http://endeavor.svc.cluster.local

  issuer: "http://quarterdeck.svc.cluster.local"

endeavor:
  origin: http://endeavor.svc.cluster.local

secrets:
  create: true
  inferenceAPIKey:
    value: "inferenceapikey"

quarterdeck:
  enabled: true
  readinessProbe: null
  livenessProbe: null