secrets:
  create: true
  inferenceAPIKey:
    value: "inferenceapikey"

ingress:
  enabled: true
  hosts:
    - host: endeavor.example.com
      paths:
        - path: /
          pathType: Prefix
    - host: endeavor.example.dev
      paths:
        - path: /
          pathType: Prefix

volumeClaimTemplates:
  # The node data spec will be included in volume claim templates.
  nodeData:
    mountPath: /data/db
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi

# set readinessProbe and livenessProbe to null to prevent connection to db.
readinessProbe: null
livenessProbe: null
