{{- if and .Values.secrets.cofferKeys.create .Values.secrets.cofferKeys.value -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "endeavor.cofferKeysSecretName" . }}
  labels:
    {{- include "endeavor.labels" . | nindent 4 }}
data:
  {{ .Values.secrets.cofferKeys.secretKey }}: {{ .Values.secrets.cofferKeys.value | b64enc }}
{{- end }}
