{{- if and .Values.genoa.enabled .Values.genoa.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.genoa.serviceAccount.name }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.genoa.serviceAccount.role }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.genoa.serviceAccount.bind }}
  labels:
    {{- include "genoa.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.genoa.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.genoa.serviceAccount.role }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}