{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "r8lapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "r8lapi.labels" . | nindent 4 }}
data:
  {{- if .Values.secrets.adminUsername.value }}
  {{ .Values.secrets.adminUsername.secretKey }}: {{ .Values.secrets.adminUsername.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.adminPassword.value }}
  {{ .Values.secrets.adminPassword.secretKey }}: {{ .Values.secrets.adminPassword.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.sendgridAPIKey.value }}
  {{ .Values.secrets.sendgridAPIKey.secretKey }}: {{ .Values.secrets.sendgridAPIKey.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hubspotAccessToken.value }}
  {{ .Values.secrets.hubspotAccessToken.secretKey }}: {{ .Values.secrets.hubspotAccessToken.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hubspotPortalID.value }}
  {{ .Values.secrets.hubspotPortalID.secretKey }}: {{ .Values.secrets.hubspotPortalID.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hubspotContactFormID.value }}
  {{ .Values.secrets.hubspotContactFormID.secretKey }}: {{ .Values.secrets.hubspotContactFormID.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hubspotEndeavorFormID.value }}
  {{ .Values.secrets.hubspotEndeavorFormID.secretKey }}: {{ .Values.secrets.hubspotEndeavorFormID.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.hubspotNewsletterFormID.value }}
  {{ .Values.secrets.hubspotNewsletterFormID.secretKey }}: {{ .Values.secrets.hubspotNewsletterFormID.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.recaptchaProjectID.value }}
  {{ .Values.secrets.recaptchaProjectID.secretKey }}: {{ .Values.secrets.recaptchaProjectID.value | b64enc }}
  {{- end }}
  {{- if .Values.secrets.recaptchaSecretKey.value }}
  {{ .Values.secrets.recaptchaSecretKey.secretKey }}: {{ .Values.secrets.recaptchaSecretKey.value | b64enc }}
  {{- end }}
{{- end -}}
