apiVersion: v1
kind: Service
metadata:
  name: {{ include "r8lapi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "r8lapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "r8lapi.selectorLabels" . | nindent 4 }}
